name: refresh-data

on:
  schedule:
  - cron: '*/30 00-01 * * *'
push:
  branches:
  - master

jobs:
  refresh-data:
  runs-on: macOS-latest
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
steps:
  - uses: actions/checkout@v2
- uses: r-lib/actions/setup-r@master
- uses: r-lib/actions/setup-pandoc@v1
- name: Install packages
run: Rscript -e 'install.packages(c("tidyverse", "tesseract", "magick", "here"), type = "binary")'
- name: Get data
run: Rscript -e 'source(here::here("R", "scrape_cash_rate.R"), echo = TRUE)'
- name: Commit
run: |
  git config --global user.name 'Matt Cowgill'
git config --global user.email 'mattcowgill@github.com'
git add .
git commit -m 'refreshing data' || echo "No changes to commit"
git push || echo "No changes to commit"
